[package]
name = "dam-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "5.5.0"
enum_delegate = "0.2.0"
home = "0.5.5"
linkme = "0.3.12"
log = "0.4.19"
serde = {version = "1.0.171", features=["derive"]}
serde_json = "1.0.101"
toml = { version = "0.7.6", feature = ["preserve_order"]}
dam-macros = { version = "0.1.0", path = "../dam-macros" }
rustc-hash = "1.1.0"

